### ISSUE TITLE
Users falling off the screen in the shapeshifter menu

### ISSUE THREAD

**Issue by RobinRMC** [CrowdedMods/CrowdedMod#42]

**Comment by Galster-dev** [comment]
Hello.

Try with [this build](https://github.com/CrowdedMods/CrowdedMod/actions/runs/2592924259)

**Comment by Tommy-XL** [comment]
This patch shows the wrong number of pages on the vote
![IMG_20220701_154904](https://user-images.githubusercontent.com/104814436/176850064-d66ceeed-a645-42f0-a0f4-c8eba6341adf.png)

**Comment by Galster-dev** [comment]
This small issue [should be fixed](https://github.com/CrowdedMods/CrowdedMod/actions/runs/2601434741)

**Comment by Tommy-XL** [comment]
In this patch, everything was fixed, no errors were found

**Comment by Galster-dev** [comment]
@RobinRMC

**Comment by RobinRMC** [comment]
I haven't had the time to test anything, and I still don't. I trust @Tommy-XL and hope it is fixed.

**Comment by Tommy-XL** [comment]
I think the question can be closed, because I decided to check for 126 Dummy and as a result did not notice any bugs
